/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package livro;

/**
 *
 * @author Usuário
 */
public class Interface extends javax.swing.JFrame {
    Livro l = new Livro();
    Livro l2 = new Livro();
    Livro l3 = new Livro();
    Livro l4 = new Livro();
     
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        ctxt_titulo = new javax.swing.JTextField();
        ctxt_autor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ctxt_Editora = new javax.swing.JTextField();
        ctxt_Isbn = new javax.swing.JTextField();
        ctxt_QtdP = new javax.swing.JTextField();
        ctxt_Vl = new javax.swing.JTextField();
        ctxt_Ano = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_monstrar = new javax.swing.JButton();
        lblMostrar = new javax.swing.JLabel();
        btnvenda = new javax.swing.JButton();
        ctxt_qtd = new javax.swing.JTextField();
        lblQtd = new javax.swing.JLabel();
        lbl_venda = new javax.swing.JLabel();
        BtnRegistrar2 = new javax.swing.JButton();
        BtnRegistrar4 = new javax.swing.JButton();
        BtnRegistrar3 = new javax.swing.JButton();
        btn_monstrar1 = new javax.swing.JButton();
        btn_monstrar2 = new javax.swing.JButton();
        btn_monstrar3 = new javax.swing.JButton();
        btnvenda1 = new javax.swing.JButton();
        btnvenda2 = new javax.swing.JButton();
        btnvenda3 = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ctxt_titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxt_tituloActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        jLabel2.setText("Autor");

        ctxt_Isbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxt_IsbnActionPerformed(evt);
            }
        });

        ctxt_Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxt_AnoActionPerformed(evt);
            }
        });

        BtnRegistrar.setText("Registrar#1");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Editora");

        jLabel4.setText("Isbn");

        jLabel5.setText("Ano");

        jLabel6.setText("Qtd Paginas");

        jLabel7.setText("Valor");

        btn_monstrar.setText("Mostrar#1");
        btn_monstrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monstrarActionPerformed(evt);
            }
        });

        btnvenda.setText("Venda#1");
        btnvenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvendaActionPerformed(evt);
            }
        });

        ctxt_qtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctxt_qtdActionPerformed(evt);
            }
        });

        BtnRegistrar2.setText("Registrar#2");
        BtnRegistrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar2ActionPerformed(evt);
            }
        });

        BtnRegistrar4.setText("Registrar#4");
        BtnRegistrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar4ActionPerformed(evt);
            }
        });

        BtnRegistrar3.setText("Registrar#3");
        BtnRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrar3ActionPerformed(evt);
            }
        });

        btn_monstrar1.setText("Mostrar#2");
        btn_monstrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monstrar1ActionPerformed(evt);
            }
        });

        btn_monstrar2.setText("Mostrar#4");
        btn_monstrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monstrar2ActionPerformed(evt);
            }
        });

        btn_monstrar3.setText("Mostrar#3");
        btn_monstrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monstrar3ActionPerformed(evt);
            }
        });

        btnvenda1.setText("Venda#3");
        btnvenda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenda1ActionPerformed(evt);
            }
        });

        btnvenda2.setText("Venda#2");
        btnvenda2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenda2ActionPerformed(evt);
            }
        });

        btnvenda3.setText("Venda#4");
        btnvenda3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenda3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ctxt_QtdP, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addComponent(ctxt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(37, 37, 37)
                                            .addComponent(jLabel3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ctxt_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BtnRegistrar)
                                            .addComponent(BtnRegistrar2))))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtnRegistrar4)
                                    .addComponent(BtnRegistrar3)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ctxt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ctxt_Isbn, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                            .addComponent(ctxt_Vl))))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(ctxt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnvenda)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnvenda1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnvenda2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnvenda3)))
                                .addGap(0, 200, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_monstrar)
                                            .addComponent(btn_monstrar1))
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel1)
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5)
                                .addGap(141, 141, 141)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_monstrar3)
                    .addComponent(btn_monstrar2))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ctxt_Editora, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_monstrar)
                            .addComponent(btn_monstrar3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_monstrar2)
                            .addComponent(btn_monstrar1))
                        .addGap(18, 18, 18)
                        .addComponent(lblMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctxt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ctxt_Editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ctxt_Isbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnvenda)
                            .addComponent(ctxt_qtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(btnvenda1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnvenda2)
                                    .addComponent(btnvenda3)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ctxt_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ctxt_Vl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(ctxt_QtdP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(lbl_venda, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnRegistrar)
                                    .addComponent(BtnRegistrar3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BtnRegistrar2)
                                    .addComponent(BtnRegistrar4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(lblQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(419, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctxt_tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxt_tituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxt_tituloActionPerformed

    private void ctxt_IsbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxt_IsbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxt_IsbnActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        l.setAno(Integer.parseInt(ctxt_Ano.getText()));
        l.setIsbn(Integer.parseInt(ctxt_Isbn.getText()));
        l.setQtdPaginas(Integer.parseInt(ctxt_QtdP.getText()));
        l.setvalor(Integer.parseInt(ctxt_Vl.getText()));
        l.setAutor(ctxt_autor.getText());
        l.setEditora(ctxt_Editora.getText());
        l.setTitulo(ctxt_titulo.getText());
        System.out.println(l.Exibir());
        
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void ctxt_AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxt_AnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctxt_AnoActionPerformed

    private void btn_monstrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monstrarActionPerformed
        lblMostrar.setText(l.Exibir());
    }//GEN-LAST:event_btn_monstrarActionPerformed

    private void ctxt_qtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctxt_qtdActionPerformed
        l.Venda(Integer.parseInt(ctxt_qtd.getText()));
    }//GEN-LAST:event_ctxt_qtdActionPerformed

    private void btnvendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvendaActionPerformed
        lblQtd.setText(String.valueOf((l.Venda(Integer.parseInt(ctxt_qtd.getText())))));
    }//GEN-LAST:event_btnvendaActionPerformed

    private void BtnRegistrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar2ActionPerformed
        l2.setAno(Integer.parseInt(ctxt_Ano.getText()));
        l2.setIsbn(Integer.parseInt(ctxt_Isbn.getText()));
        l2.setQtdPaginas(Integer.parseInt(ctxt_QtdP.getText()));
        l2.setvalor(Integer.parseInt(ctxt_Vl.getText()));
        l2.setAutor(ctxt_autor.getText());
        l2.setEditora(ctxt_Editora.getText());
        l2.setTitulo(ctxt_titulo.getText());
    }//GEN-LAST:event_BtnRegistrar2ActionPerformed

    private void BtnRegistrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar4ActionPerformed
        l4.setAno(Integer.parseInt(ctxt_Ano.getText()));
        l4.setIsbn(Integer.parseInt(ctxt_Isbn.getText()));
        l4.setQtdPaginas(Integer.parseInt(ctxt_QtdP.getText()));
        l4.setvalor(Integer.parseInt(ctxt_Vl.getText()));
        l4.setAutor(ctxt_autor.getText());
        l4.setEditora(ctxt_Editora.getText());
        l4.setTitulo(ctxt_titulo.getText());
    }//GEN-LAST:event_BtnRegistrar4ActionPerformed

    private void BtnRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrar3ActionPerformed
        l3.setAno(Integer.parseInt(ctxt_Ano.getText()));
        l3.setIsbn(Integer.parseInt(ctxt_Isbn.getText()));
        l3.setQtdPaginas(Integer.parseInt(ctxt_QtdP.getText()));
        l3.setvalor(Integer.parseInt(ctxt_Vl.getText()));
        l3.setAutor(ctxt_autor.getText());
        l3.setEditora(ctxt_Editora.getText());
        l3.setTitulo(ctxt_titulo.getText());
    }//GEN-LAST:event_BtnRegistrar3ActionPerformed

    private void btn_monstrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monstrar1ActionPerformed
        lblMostrar.setText(l2.Exibir());
    }//GEN-LAST:event_btn_monstrar1ActionPerformed

    private void btn_monstrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monstrar2ActionPerformed
        lblMostrar.setText(l4.Exibir());
    }//GEN-LAST:event_btn_monstrar2ActionPerformed

    private void btn_monstrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monstrar3ActionPerformed
        lblMostrar.setText(l3.Exibir());
    }//GEN-LAST:event_btn_monstrar3ActionPerformed

    private void btnvenda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenda1ActionPerformed
        lblQtd.setText(String.valueOf((l3.Venda(Integer.parseInt(ctxt_qtd.getText())))));
    }//GEN-LAST:event_btnvenda1ActionPerformed

    private void btnvenda2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenda2ActionPerformed
        lblQtd.setText(String.valueOf((l2.Venda(Integer.parseInt(ctxt_qtd.getText())))));
    }//GEN-LAST:event_btnvenda2ActionPerformed

    private void btnvenda3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenda3ActionPerformed
        lblQtd.setText(String.valueOf((l4.Venda(Integer.parseInt(ctxt_qtd.getText())))));
    }//GEN-LAST:event_btnvenda3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JButton BtnRegistrar2;
    private javax.swing.JButton BtnRegistrar3;
    private javax.swing.JButton BtnRegistrar4;
    private javax.swing.JButton btn_monstrar;
    private javax.swing.JButton btn_monstrar1;
    private javax.swing.JButton btn_monstrar2;
    private javax.swing.JButton btn_monstrar3;
    private javax.swing.JButton btnvenda;
    private javax.swing.JButton btnvenda1;
    private javax.swing.JButton btnvenda2;
    private javax.swing.JButton btnvenda3;
    private javax.swing.JTextField ctxt_Ano;
    private javax.swing.JTextField ctxt_Editora;
    private javax.swing.JTextField ctxt_Isbn;
    private javax.swing.JTextField ctxt_QtdP;
    private javax.swing.JTextField ctxt_Vl;
    private javax.swing.JTextField ctxt_autor;
    private javax.swing.JTextField ctxt_qtd;
    private javax.swing.JTextField ctxt_titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblMostrar;
    private javax.swing.JLabel lblQtd;
    private javax.swing.JLabel lbl_venda;
    // End of variables declaration//GEN-END:variables
}
